import React, { useEffect, useState } from 'react';
import {
  FileBarChart,
  Download,
  Filter,
  Calendar,
  Layers,
  Flame,
  Droplet,
  CheckCircle2
} from 'lucide-react';
import api from '../../services/api';

export const ReportsPage: React.FC = () => {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [reportType, setReportType] = useState('ALL');

  useEffect(() => {
    const params: any = {};
    if (reportType !== 'ALL') params.type = reportType;

    api.get('/reports', { params })
      .then((res) => setReports(res.data))
      .catch((err) => console.error('Failed to load reports:', err))
      .finally(() => setLoading(false));
  }, [reportType]);

  const handleExportCsv = (type: string) => {
    window.open(`/api/reports/export?type=${type}`, '_blank');
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-white tracking-wide">Reports & Production Analytics</h1>
            <span className="text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 font-mono">
              AUDITED DATASETS
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-0.5 font-mono">
            Field Production Summaries • Thermal Efficiency Metrics • CSV Operational Exports
          </p>
        </div>

        <div className="flex items-center gap-3">
          <select
            value={reportType}
            onChange={(e) => setReportType(e.target.value)}
            className="bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-white font-mono"
          >
            <option value="ALL">All Report Types</option>
            <option value="PRODUCTION">Production Reports</option>
            <option value="STEAM_EFFICIENCY">Steam Efficiency</option>
          </select>

          <button
            onClick={() => handleExportCsv('PRODUCTION')}
            className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-black font-bold text-xs font-mono transition-all"
          >
            <Download className="w-4 h-4" />
            <span>Export CSV</span>
          </button>
        </div>
      </div>

      {/* Reports Grid */}
      <div className="space-y-4">
        {reports.map((rep) => (
          <div key={rep.id} className="petro-card p-5 border-slate-800 space-y-3">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800/80 pb-3">
              <div>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-900 text-cyan-400 font-semibold uppercase">
                  {rep.type}
                </span>
                <h3 className="text-base font-bold text-white mt-1">{rep.title}</h3>
              </div>
              <div className="text-xs font-mono text-slate-400">
                Generated By: <strong className="text-white">{rep.generatedBy}</strong> • {new Date(rep.createdAt).toLocaleDateString()}
              </div>
            </div>

            <p className="text-xs text-slate-300 leading-relaxed font-sans">{rep.summary}</p>

            {rep.data && (
              <div className="p-3 rounded-xl bg-slate-900/60 border border-slate-800 font-mono text-xs">
                <span className="text-[10px] text-slate-400 uppercase tracking-wider block mb-2 font-bold">
                  Report Telemetry Metrics:
                </span>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  {Object.entries(rep.data).map(([key, val]) => (
                    <div key={key}>
                      <span className="text-[10px] text-slate-500 block uppercase">
                        {key.replace(/([A-Z])/g, ' $1')}
                      </span>
                      <span className="text-sm font-bold text-cyan-300">
                        {typeof val === 'number' ? val.toFixed(1) : String(val)}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};
